# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.2"
# path of deployment config file
deployment = "deployment.toml"

[[contracts]]
name = "joyid-cobuild-poc"
template_type = "Rust"
